import { SyntaxEntry } from "../../types";
import { joinLines } from "../../syntax/entries/helpers";

export const helpBlockEntry: SyntaxEntry = {
  id: "help-block",
  title: { en: "Help / hint block", de: "Hilfe-/Hinweis-Block" },
  markers: ["#help", "#helpend"],
  keyRule: {
    en: "Hints live in #help ... #helpend and never affect grading.",
    de: "Hinweise stehen in #help ... #helpend und beeinflussen keine Bewertung.",
  },
  snippet: {
    en: "#help\nHint: {{...}}\n#helpend",
    de: "#help\nHinweis: {{...}}\n#helpend",
  },
  detail: {
    en: {
      whatItIs:
        "The help block is a non-graded hint area. If a #help ... #helpend block exists, the UI can show it as optional guidance without changing the detected interaction type or scoring.",
      rules: [
        "Place #help ... #helpend inside a #card ... #endcard block or inside an exam task.",
        "#help and #helpend must be on their own lines.",
        "Hints are optional and only shown if the block exists.",
        "Help content never affects grading or the detected card type.",
        "Keep hints short and supportive; avoid full solutions unless intentional.",
      ],
      promptTemplate: joinLines([
        "Write exactly one flashcard in FMDFlashcard syntax.",
        "Return only the #card block.",
        "Add exactly one #help ... #helpend block with short hints.",
        "Rules:",
        "- The help block must be inside the #card block.",
        "- #help and #helpend must be on their own lines.",
        "- Keep hints short; do not reveal the full solution.",
        "Template:",
        "#card",
        "{{prompt}}",
        "{{interaction_body}}",
        "",
        "#help",
        "{{hint_intro}}",
        "- {{hint_1}}",
        "- {{hint_2}}",
        "#helpend",
        "#endcard",
      ]),
      example: joinLines([
        "#card",
        "Which number is a prime number?",
        "a) 4",
        "b) 5",
        "c) 9",
        "-b",
        "",
        "#help",
        "Key idea: A prime has exactly two divisors (1 and itself).",
        "- Check divisibility by 2 or 3 first.",
        "- If it has another divisor, it is not prime.",
        "#helpend",
        "#endcard",
      ]),
      mistakes: [
        "Forgetting #helpend (the help block may swallow following lines).",
        "Placing #help outside any card or exam task (it will be ignored).",
        "Using #help for graded answers or solutions by accident.",
      ],
    },
    de: {
      whatItIs:
        "Der Help-Block ist ein nicht-bewerteter Hinweisbereich. Wenn ein #help ... #helpend Block existiert, kann die UI ihn optional anzeigen, ohne Kartentyp oder Bewertung zu aendern.",
      rules: [
        "#help ... #helpend innerhalb eines #card ... #endcard Blocks oder innerhalb einer Exam-Aufgabe platzieren.",
        "#help und #helpend muessen jeweils auf eigenen Zeilen stehen.",
        "Hinweise sind optional und werden nur angezeigt, wenn der Block existiert.",
        "Help-Inhalt beeinflusst weder Kartentyp noch Bewertung.",
        "Hinweise kurz halten; keine komplette Loesung verraten (ausser absichtlich).",
      ],
      promptTemplate: joinLines([
        "Erstelle genau eine Flashcard im FMDFlashcard-Syntaxformat.",
        "Gib nur den #card-Block zurueck.",
        "Fuege genau einen #help ... #helpend Block mit kurzen Hinweisen hinzu.",
        "Regeln:",
        "- Der Help-Block muss innerhalb des #card-Blocks stehen.",
        "- #help und #helpend muessen auf eigenen Zeilen stehen.",
        "- Hinweise kurz halten; keine komplette Loesung verraten.",
        "Template:",
        "#card",
        "{{frage}}",
        "{{interaktion}}",
        "",
        "#help",
        "{{hinweis_intro}}",
        "- {{hinweis_1}}",
        "- {{hinweis_2}}",
        "#helpend",
        "#endcard",
      ]),
      example: joinLines([
        "#card",
        "Welche Zahl ist eine Primzahl?",
        "a) 4",
        "b) 5",
        "c) 9",
        "-b",
        "",
        "#help",
        "Merksatz: Eine Primzahl hat genau zwei Teiler (1 und sich selbst).",
        "- Pruefe zuerst Teilbarkeit durch 2 oder 3.",
        "- Gibt es einen weiteren Teiler, ist es keine Primzahl.",
        "#helpend",
        "#endcard",
      ]),
      mistakes: [
        "#helpend vergessen (der Block kann nachfolgende Zeilen verschlucken).",
        "#help ausserhalb einer Karte oder Exam-Aufgabe platzieren (wird ignoriert).",
        "#help fuer bewertete Antworten verwenden (sollte nur Hinweis sein).",
      ],
    },
  },
};
