import { SyntaxEntry } from "../../types";
import { joinLines } from "../../syntax/entries/helpers";

const promptExamTemplateDe = joinLines([
  "Du bist ein Exam-Generator für ein Markdown-basiertes Lernsystem.",
  "",
  "ERZEUGE als Output genau EINE Markdown-Datei im folgenden Format:",
  "- Beginne mit #exam und ende mit #examend. (Beides jeweils als eigene Zeile.)",
  "- Erstelle KEINE #card-Blöcke.",
  "- Jede Aufgabe ist ein nummerierter Exam-Task (1) bis 10)).",
  "  Hinweis: In Exam-Tasks endet eine Aufgabe beim nächsten nummerierten Start oder bei #examend; nutze daher klare Nummerierung.",
  "",
  "THEMA (vom Nutzer vorgegeben): <THEMA_EINSETZEN>",
  "KONTEXT (optional): <KURS/Modul/IU-Kontext_EINSETZEN>",
  "SPRACHE: Deutsch",
  "SCHWIERIGKEIT: Klausurniveau (präzise, prüfungsnah)",
  "",
  "ZEIT & UMFANG:",
  "- Gesamtzeit: 45 Minuten",
  "- Schreibrate-Referenz: 8 Wörter/Minute → ca. 360 Wörter Gesamtschreibvolumen",
  "- Ziel für Textaufgaben (Abschnitte 2–4): jeweils ~90 Wörter, mit Absätzen und Unterpunkten.",
  "(so, wie man es in einer Klausur sauber schreiben würde)",
  "---",
  "falls frommeln benötigt werden diese in  $ FormelXYZ $ oder in",
  "$$ \\text{Latext} = \\frac{\\text{Wert/Variabele/Oparatzion/Einheiten}}{\\text{Wert/Variabele/Oparatzion/Einheiten}} $$ Dargestellt",
  "falls code block innhelb der code block benötigt alos ```",
  "```sql",
  "code",
  "```",
  "oder",
  "```c++",
  "code",
  "```",
  "---",
  "",
  "AUFGABEN-ANFORDERUNGEN:",
  "1) Abschnitt 1:",
  "- Erstelle 1 Aufgabe als m2",
  "  - m2: Optionen a) b) c) d) und genau EIN ZWEI DREI ODER VIER, korrekte Marker-Zeichen wie -a -b -c -d",
  "2)–5) Abschnitt 1:",
  "- Erstelle 4 Aufgaben als m1",
  "  - m1: Optionen a) b) c) d) und genau EIN korrektes Marker-Zeichen wie -a -b -c -d",
  "6)–7) Abschnitt 1:",
  "- Erstelle 2 Aufgabe als 2 teilaugaben tf = True/False mit einer m1 = a) b) c) d): und EIN korrektes Marker-Zeichen wie -a -b -c -d",
  "7) Quest: test",
  "a)",
  "b)",
  "c)",
  "d)",
  "-x",
  "Statement:",
  "Aussage",
  "-true or -false",
  "",
  "  - Aussage/Prompt",
  "  - In der nächsten nicht-leeren Zeile: -true oder -false",
  "- Jede dieser Aufgaben muss vollständig selbstständig sein (klarer Prompt, eindeutige Optionen).",
  "- KEINE Lösung als Fließtext; bei m1/m2/tf reicht der Marker als “offiziell”.",
  "-Jede aufgabe bekommt nur eine nummerierter Exam-Task!",
  "---",
  "1) Abschnitt 2 – Begriffsdefinitionen:",
  "- Nutze qa mit einem offiziellen Lösungsteil über einen Antwortmarker:",
  "  - Schreibe nach dem Prompt eine Zeile, die mit \"Antwort:\" beginnt, und liefere eine Musterdefinition mit 2–4 Unterpunkten.",
  "    (unterpunkte nur mit - verwenden naimals zahlen).",
  "  - Die Musterlösung muss präzise und klausurtauglich formuliert sein. (Antwortmarker werden zeilenbasiert erfasst.)",
  "  - erstell ein Helpblock mit #help in dem du Dazwischen Hifestellungen zeigst #helpend",
  "---",
  "1) Abschnitt 3 – Erläuterungsfrage:",
  "- Nutze qa:",
  "  - Prompt verlangt strukturierte Erklärung (Absätze + Unterpunkte ) (unterpunkte nur mit - verwenden naimals zahlen).",
  "  - Danach \"Antwort:\" und eine Musterlösung (ebenfalls strukturiert), inkl. 2–3 Kernaussagen + 1 kurzes Beispiel.",
  "    - Tabelle können müssen aber nicht zur aufgabenstellung gehören.",
  "- erstell ein Helpblock mit #help in dem du Dazwischen Hifestellungen zeigst #helpend",
  "7) Abschnitt 4 – Anwendungsfrage mit Code und Tabelle in der Aufgabenstellung:",
  "- Nutze cld (Kombination aus Typed Blanks und Drag Tokens):",
  "  - Integriere in den Aufgabentext:",
  "    - mindestens 3 Typed Blanks im Format %%...%%",
  "    - mindestens 5 Drag Tokens im Format tocken \"token\"",
  "  - Kontext ist ein realistischer Mini-Use-Case (z. B. Code-Review, Bugfix, API-Call, SQL-Query, Konfig-Snippet).",
  "  - Aufgabe muss eine echte Anwendung prüfen (nicht nur Definition) anwendungs code Darf nicht Länger als 7 Zeilen Code Sein!.",
  "  - Verwende Tokens so, dass es “Zuordnung”/Einsetzen in Lücken oder drag and drob ermöglicht.",
  "  - Drag Tokens dürfen niemals erklärt oder gelistet werden; sie müssen exakt dort im Aufgaben-/Code-Text stehen, wo sie syntaktisch und semantisch hingehören, damit das System die Drag-Lücken automatisch an genau diesen Positionen erzeugt.",
  "  - Gib eine separate Fließtextlösung; die Lösungen als antwort abschluss der Anwendungsfrage.",
  "  - Anwendungsfrage als \"Antwort:\" und eine Musterlösung (ebenfalls strukturiert), inkl. 2–3 Kernaussagen + 1 kurzes Beispiel.",
  "  - erstell ein Helpblock mit #help in dem du Dazwischen Hifestellungen zeigst #helpend",
  "---",
  "FORMATREGELN:",
  "- Jede Aufgabe beginnt mit \"1)\" bzw. \"2)\" etc. (eine Zeile).",
  "- Nutze klare Überschriften für die Abschnitte (z. B. \"📍 Abschnitt 1: ...\").",
  "- Vermeide horizontale Trenner '---' innerhalb von Antworten/Fließtext, um nicht versehentlich Aufgaben zu terminieren.",
  "- aber verwende Tennlienen --- nach jeder Aufgabe",
  "- Output muss am Ende mit #examend schließen.",
  "",
  "GIB DIE AUFGABEN ALS DOWNLOADBARE DATEI AUS !",
]);

const promptExamTemplateEn = joinLines([
  "You are an exam generator for a Markdown-based learning system.",
  "",
  "GENERATE as output exactly ONE Markdown file in the following format:",
  "- Start with #exam and end with #examend. (Each on its own line.)",
  "- Create NO #card blocks.",
  "- Each task is a numbered exam task (1) to 10)).",
  "  Note: In exam tasks, a task ends at the next numbered start or at #examend; therefore use clear numbering.",
  "",
  "TOPIC (provided by the user): <INSERT_TOPIC>",
  "CONTEXT (optional): <INSERT_COURSE/MODULE/IU_CONTEXT>",
  "LANGUAGE: German",
  "DIFFICULTY: Exam level (precise, exam-oriented)",
  "",
  "TIME & SCOPE:",
  "- Total time: 45 minutes",
  "- Writing rate reference: 8 words/minute → approx. 360 words total writing volume",
  "- Target for text tasks (sections 2–4): about ~90 words each, with paragraphs and sub-bullets.",
  "  (as one would write cleanly in an exam)",
  "---",
  "If formulas are needed, display them in $ FormulaXYZ $ or in",
  "$$ \\text{LaTeX} = \\frac{\\text{value/variable/operation/units}}{\\text{value/variable/operation/units}} $$",
  "If a code block within a code block is ```.",
  "```sql",
  "code",
  "```",
  "or",
  "```c++",
  "code",
  "```",
  "---",
  "",
  "TASK REQUIREMENTS:",
  "1) Section 1:",
  "- Create 1 task as m2",
  "  - m2: options a) b) c) d) and exactly ONE TWO THREE OR FOUR, correct marker characters like -a -b -c -d",
  "2)–5) Section 1:",
  "- Create 4 tasks as m1",
  "  - m1: options a) b) c) d) and exactly ONE correct marker character like -a -b -c -d",
  "6)–7) Section 1:",
  "- Create 2 tasks as 2 sub-tasks tf = True/False with an m1 = a) b) c) d): and ONE correct marker character like -a -b -c -d",
  "7) Quest: test",
  "a)",
  "b)",
  "c)",
  "d)",
  "-x",
  "Statement:",
  "Assertion",
  "-true or -false",
  "",
  "  - Assertion/prompt",
  "  - On the next non-empty line: -true or -false",
  "- Each of these tasks must be fully self-contained (clear prompt, unambiguous options).",
  "- NO solution as running text; for m1/m2/tf the marker is sufficient as “official”.",
  "- Each task gets only one numbered exam task!",
  "---",
  "1) Section 2 – Term definitions:",
  "- Use qa with an official solution part via an answer marker:",
  "  - After the prompt, write a line that starts with \"Antwort:\" and provide a model definition with 2–4 sub-bullets.",
  "    (sub-bullets only with -; never numbers).",
  "  - The model solution must be precise and suitable for an exam. (Answer markers are captured line-based.)",
  "  - Create a help block with #help where you show hints in between, ending with #helpend",
  "---",
  "1) Section 3 – Explanation question:",
  "- Use qa:",
  "  - Prompt requires a structured explanation (paragraphs + sub-bullets) (sub-bullets only with -; never numbers).",
  "  - Then \"Antwort:\" and a model solution (also structured), incl. 2–3 key statements + 1 short example.",
  "    - Tables may but do not have to be part of the task statement.",
  "- Create a help block with #help where you show hints in between, ending with #helpend",
  "7) Section 4 – Application question with code and table in the task statement:",
  "- Use cld (combination of Typed Blanks and Drag Tokens):",
  "  - Integrate into the task text:",
  "    - at least 3 Typed Blanks in the format %%...%%",
  "    - at least 5 Drag Tokens in the format tocken \"token\"",
  "  - Context is a realistic mini use case (e.g., code review, bug fix, API call, SQL query, config snippet).",
  "  - The task must test a real application (not just definition); application code must not be longer than 7 lines of code!",
  "  - Use tokens so that it enables “assignment”/inserting into blanks or drag-and-drop.",
  "  - Drag tokens must never be explained or listed; they must appear exactly where they syntactically and semantically belong in the task/code text, so the system automatically creates the drag gaps at those positions.",
  "  - Provide a separate running-text solution; the solutions as the answer conclusion of the application question.",
  "  - Application question as \"Antwort:\" and a model solution (also structured), incl. 2–3 key statements + 1 short example.",
  "  - Create a help block with #help where you show hints in between, ending with #helpend",
  "---",
  "FORMATTING RULES:",
  "- Each task begins with \"1)\" or \"2)\" etc. (one line).",
  "- Use clear headings for sections (e.g., \"📍 Section 1: ...\").",
  "- Avoid horizontal separators '---' inside answers/running text to avoid accidentally terminating tasks.",
  "- But use separators --- after each task",
  "- Output must end with #examend.",
  "",
  "Provide the tasks as a downloadable .md file!",
]);

const promptExamTemplateDeCode = joinLines([
  "```",
  promptExamTemplateDe,
  "```",
]);

const promptExamTemplateEnCode = joinLines([
  "```",
  promptExamTemplateEn,
  "```",
]);

export const promptExamEntry: SyntaxEntry = {
  id: "prompt-exam",
  title: { en: "Prompt: Exam generator", de: "Prompt: Exam-Generator" },
  markers: ["#exam", "#examend", "[```]"],
  keyRule: {
    en: "Replace topic/context, paste the prompt, and generate one #exam file.",
    de: "Thema/Kontext ersetzen, Prompt einfuegen, genau eine #exam-Datei erzeugen.",
  },
  snippet: {
    en: "TOPIC: <INSERT_TOPIC>\nCONTEXT: <INSERT_COURSE/MODULE/IU_CONTEXT>",
    de: "THEMA: <THEMA_EINSETZEN>\nKONTEXT: <KURS/Modul/IU-Kontext_EINSETZEN>",
  },
  detail: {
    en: {
      whatItIs:
        "A copy-ready prompt that instructs an LLM to generate one complete #exam file. Replace the TOPIC/CONTEXT placeholders, paste the prompt into Chat, and run it to get a single Markdown exam.",
      rules: [
        "Replace <INSERT_TOPIC> and (optionally) <INSERT_COURSE/MODULE/IU_CONTEXT> before sending.",
        "Paste the full template into Chat as one message and run it.",
        "Keep the [```] markers intact for nested code blocks.",
        "Expect exactly one #exam ... #examend output, wrapped in a code block.",
        "Do not add #card blocks or extra files unless you intentionally change the format.",
      ],
      promptTemplate: promptExamTemplateEnCode,
      example: joinLines([
        "Example usage:",
        "TOPIC (provided by the user): Database normalization",
        "CONTEXT (optional): Intro to Relational Databases",
        "LANGUAGE: German",
        "DIFFICULTY: Exam level (precise, exam-oriented)",
        "",
        "Paste the English template with your topic/context and run it in Chat.",
      ]),
      mistakes: [
        "Leaving <INSERT_TOPIC> or <THEMA_EINSETZEN> unchanged.",
        "Deleting the [```] markers, which breaks nested code blocks.",
        "Requesting multiple files or adding #card blocks.",
        "Removing #examend or the required code block wrapper.",
      ],
    },
    de: {
      whatItIs:
        "Ein copy-fertiger Prompt, der ein LLM anweist, genau eine #exam-Datei zu erzeugen. THEMA/KONTEXT ersetzen, den Prompt in den Chat einfuegen und ausfuehren, um ein Markdown-Exam zu erhalten.",
      rules: [
        "<THEMA_EINSETZEN> und optional <KURS/Modul/IU-Kontext_EINSETZEN> ersetzen.",
        "Das komplette Template als eine Nachricht in den Chat einfuegen und starten.",
        "Die [```]-Marker fuer verschachtelte Codebloecke beibehalten.",
        "Erwarte genau eine #exam ... #examend Ausgabe im Codeblock.",
        "Keine #card-Bloecke oder zusaetzliche Dateien hinzufuegen.",
      ],
      promptTemplate: promptExamTemplateDeCode,
      example: joinLines([
        "Beispielnutzung:",
        "THEMA (vom Nutzer vorgegeben): Datenbanknormalisierung",
        "KONTEXT (optional): Einfuehrung relationale Datenbanken",
        "SPRACHE: Deutsch",
        "SCHWIERIGKEIT: Klausurniveau (praezise, pruefungsnah)",
        "",
        "Deutsches oder englisches Template mit Thema/Kontext einsetzen und im Chat ausfuehren.",
      ]),
      mistakes: [
        "<INSERT_TOPIC> oder <THEMA_EINSETZEN> nicht ersetzt.",
        "[```]-Marker entfernt, wodurch verschachtelte Codebloecke brechen.",
        "Mehrere Dateien oder #card-Bloecke angefordert.",
        "#examend oder den Codeblock entfernt.",
      ],
    },
  },
};
