import { SyntaxEntry } from "../../types";
import { joinLines } from "./helpers";

export const helpBlockEntry: SyntaxEntry = {
  id: "help-block",
  title: { en: "Help / hint block", de: "Hilfe-/Hinweis-Block" },
  markers: ["#help", "#helpend"],
  keyRule: {
    en: "Attach optional hints inside a card/task; help never affects grading.",
    de: "Optionale Hinweise innerhalb Karte/Aufgabe; Help beeinflusst keine Bewertung.",
  },
  snippet: {
    en: "#help\nHint: {{...}}\n#helpend",
    de: "#help\nHinweis: {{...}}\n#helpend",
  },
  detail: {
    en: {
      whatItIs:
        "Use #help ... #helpend to attach non-graded hints to a flashcard (or an exam task). The parser extracts the block and excludes it from interaction detection, so markers inside help do not change the detected card type or scoring.",
      rules: [
        "Place the help block inside an open #card ... # scope (or inside an ea task scope).",
        "#help and #helpend must be on their own lines.",
        "Help content is optional UI text (hints, reminders, mini cheat-sheets).",
        "Help never changes the detected interaction type and never affects scoring/SRS.",
        "Avoid a standalone '---' line inside #help (it ends the help block early).",
        "A help block outside any card/task is ignored.",
      ],
      promptTemplate: joinLines([
        "Write exactly one flashcard in FMDFlashcard syntax.",
        "Return only the #card block.",
        "Add exactly one #help ... #helpend block with short hints.",
        "Rules:",
        "- The help block must be inside the #card block.",
        "- #help and #helpend must be on their own lines.",
        "- Do not put '---' on its own line inside #help.",
        "- Do not reveal the full solution inside the hints.",
        "Template:",
        "#card",
        "{{prompt}}",
        "{{interaction_body}}",
        "",
        "#help",
        "{{hint_intro}}",
        "- {{hint_1}}",
        "- {{hint_2}}",
        "#helpend",
        "#",
      ]),
      example: joinLines([
        "#card",
        "Which number is a prime number?",
        "a) 4",
        "b) 5",
        "c) 9",
        "-b",
        "",
        "#help",
        "Key idea: A prime has exactly two divisors (1 and itself).",
        "- Check divisibility by 2 or 3 first.",
        "- If it has another divisor, it is not prime.",
        "#helpend",
        "#",
      ]),
      mistakes: [
        "Placing #help outside any #card (it will be ignored).",
        "Forgetting #helpend (the help block may swallow following lines).",
        "Using a standalone '---' inside #help (it ends the block early).",
        "Expecting Answer:/-a/-true inside #help to count as solutions (they are ignored).",
      ],
    },
    de: {
      whatItIs:
        "Mit #help ... #helpend kannst du nicht-bewertete Hinweise an eine Flashcard (oder eine Exam-Aufgabe) haengen. Der Parser extrahiert den Block und entfernt ihn vor der Interaktions-Erkennung, daher aendert Help weder Kartentyp noch Bewertung.",
      rules: [
        "Platziere den Help-Block innerhalb eines offenen #card ... #-Scopes (oder innerhalb eines ea-Task-Scopes).",
        "#help und #helpend muessen jeweils auf eigenen Zeilen stehen.",
        "Help-Inhalt ist optionaler UI-Text (Hinweise, Merksaetze, Mini-Spickzettel).",
        "Help aendert weder den erkannten Interaktionstyp noch Bewertung/SRS.",
        "Vermeide eine alleinstehende '---'-Zeile innerhalb #help (beendet den Block vorzeitig).",
        "Ein Help-Block ausserhalb einer Karte/Aufgabe wird ignoriert.",
      ],
      promptTemplate: joinLines([
        "Erstelle genau eine Flashcard im FMDFlashcard-Syntaxformat.",
        "Gib nur den #card-Block zurueck.",
        "Fuege genau einen #help ... #helpend Block mit kurzen Hinweisen hinzu.",
        "Regeln:",
        "- Der Help-Block muss innerhalb des #card-Blocks stehen.",
        "- #help und #helpend muessen auf eigenen Zeilen stehen.",
        "- Schreibe '---' nicht als eigene Zeile innerhalb #help.",
        "- Keine komplette Loesung in den Hinweisen verraten.",
        "Template:",
        "#card",
        "{{frage}}",
        "{{interaktion}}",
        "",
        "#help",
        "{{hinweis_intro}}",
        "- {{hinweis_1}}",
        "- {{hinweis_2}}",
        "#helpend",
        "#",
      ]),
      example: joinLines([
        "#card",
        "Welche Zahl ist eine Primzahl?",
        "a) 4",
        "b) 5",
        "c) 9",
        "-b",
        "",
        "#help",
        "Merksatz: Eine Primzahl hat genau zwei Teiler (1 und sich selbst).",
        "- Pruefe zuerst Teilbarkeit durch 2 oder 3.",
        "- Gibt es einen weiteren Teiler, ist es keine Primzahl.",
        "#helpend",
        "#",
      ]),
      mistakes: [
        "#help ausserhalb eines #card-Blocks platzieren (wird ignoriert).",
        "#helpend vergessen (der Block kann nachfolgende Zeilen verschlucken).",
        "Eine alleinstehende '---'-Zeile innerhalb #help verwenden (beendet den Block vorzeitig).",
        "Erwarten, dass Answer:/-a/-true innerhalb #help als Loesung zaehlt (wird ignoriert).",
      ],
    },
  },
};
