export const MARKDOWN_CODE_HIGHLIGHT_CONFIG = {
  autoDetectWithoutLanguage: false,
  showLanguageLabel: true,
  highlightInContentEditable: true,
  autoDetectCandidateLanguages: [
    "bash",
    "c",
    "cpp",
    "csharp",
    "css",
    "diff",
    "dockerfile",
    "go",
    "graphql",
    "groovy",
    "ini",
    "java",
    "javascript",
    "json",
    "kotlin",
    "latex",
    "less",
    "lua",
    "makefile",
    "markdown",
    "matlab",
    "objectivec",
    "perl",
    "php",
    "powershell",
    "python",
    "r",
    "ruby",
    "rust",
    "scala",
    "sql",
    "swift",
    "toml",
    "typescript",
    "vbnet",
    "xml",
    "yaml",
  ] as const,
} as const;

export type MarkdownCodeHighlightConfig = typeof MARKDOWN_CODE_HIGHLIGHT_CONFIG;
